name: 'cdktf-cli'
description: 'Custom action to provide access to CDKTF cli'
inputs:
  action:
    description: 'cdktf action to run'
    required: true
  workdirs:
    description: 'workdir path to run cdktf in'
    required: true
    default: '.'

runs:
  using: composite
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run plan
      if: ${{ inputs.action == 'plan' }}
      id: plan
      run: plan.sh
      shell: bash
      env:
        WORKDIRS: ${{ inputs.workdirs }}
    - name: deploy
      if: ${{ inputs.action == 'deploy' }}
      run: deploy.sh
      shell: bash
      env:
        WORKDIRS: ${{ inputs.workdirs }}
    - name: destroy
      if: ${{ inputs.action == 'destroy' }}
      run: destroy.sh
      shell: bash
      env:
        WORKDIRS: ${{ inputs.workdirs }}
