name: 'cdktf-cli'
description: 'Custom action to provide access to CDKTF cli'
inputs:
  action:
    description: 'cdktf action to run'
    required: true
  workdir:
    description: 'workdir path to run cdktf in'
    required: true
    default: '.'

outputs:
  drift:
    description: 'drift status'
    value: ${{ steps.plan.outputs.drift-status }}

runs:
  using: composite
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run plan
      if: ${{ inputs.action == 'plan' }}
      id: plan
      run: plan.sh ${{ inputs.workdir }}
      shell: bash
    - name: deploy
      if: ${{ inputs.action == 'deploy' }}
      id: deploy
      run: deploy.sh ${{ inputs.workdir }}
      shell: bash
